'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { hostView } from '@/server/service';
import type { Mode } from '@/domain/engine';
type View=ReturnType<typeof hostView>;
type Action='preflight'|'arm'|'start'|'pause'|'resume'|'stop'|'advance'|'fire'|'delay'|'skip'|'reset';
const duration=(ms:number)=>{const s=Math.floor(ms/1000);return `${Math.floor(s/3600).toString().padStart(2,'0')}:${Math.floor(s/60)%60<10?'0':''}${Math.floor(s/60)%60}:${(s%60).toString().padStart(2,'0')}`;};
const wall=(n:number)=>new Date(n).toLocaleTimeString('de-DE',{timeZone:'Europe/Berlin',hour:'2-digit',minute:'2-digit',second:'2-digit'});
function Confirm({action,onCancel,onConfirm}:{action:{action:Action;eventId?:string};onCancel:()=>void;onConfirm:(reason:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [reason,setReason]=useState('');
 useEffect(()=>{dialog.current?.showModal();},[]);
 const safety=action.action==='stop';
 const reset=action.action==='reset';
 return <dialog ref={dialog} onCancel={onCancel} aria-labelledby="confirm-title"><form onSubmit={e=>{e.preventDefault();onConfirm(safety?'Bewusst bestätigter globaler Safety-Stop.':reset?'Bewusst bestätigter Test Reset.':reason);}}>
  <span className="eyebrow">{safety?'SAFETY':reset?'NUR TEST MODE':'MANUAL OVERRIDE'}</span><h2 id="confirm-title">{safety?'Alles sicher stoppen?':reset?'Test Run zurücksetzen?':'Event bewusst ändern'}</h2>
  <p>{safety?'Alle Player sehen einen neutralen Zustand. Automation bleibt dauerhaft gesperrt.':reset?'Der alte Test Run bleibt im Audit-Archiv. Der Live Run wird nicht verändert.':'Abhängigkeiten und Safety-Sperren bleiben wirksam. Die Änderung wird im Event Log gespeichert.'}</p>
  {!safety&&!reset&&<label>Begründung<input value={reason} onChange={e=>setReason(e.target.value)} required maxLength={300} autoFocus placeholder="Warum greifst du ein?"/></label>}
  <div className="button-row"><button type="button" className="quiet" onClick={onCancel}>Abbrechen</button><button className={safety?'danger':'primary'} type="submit">{safety?'STOP ALL bestätigen':reset?'Test Reset bestätigen':'Änderung bestätigen'}</button></div>
 </form></dialog>;
}
export default function Control(){
 const requestEpoch=useRef(0);
 const [view,setView]=useState<View|null>(null),[mode,setMode]=useState<Mode>('test'),[needsLogin,setNeedsLogin]=useState(false),[secret,setSecret]=useState(''),[error,setError]=useState(''),[online,setOnline]=useState(true),[busy,setBusy]=useState(false),[links,setLinks]=useState<Record<string,string>>({}),[confirmation,setConfirmation]=useState<{action:Action;eventId?:string}|null>(null),[tab,setTab]=useState<'live'|'preflight'|'log'>('live');
 const load=useCallback(async()=>{
  const epoch=requestEpoch.current;
  try{const r=await fetch(`/api/host/state?mode=${mode}`,{cache:'no-store'});const d=await r.json();if(epoch!==requestEpoch.current)return;if(r.status===401){setNeedsLogin(true);setView(null);return;}if(!r.ok)throw new Error(d.error);setView(d);setNeedsLogin(false);setOnline(true);}catch{if(epoch===requestEpoch.current)setOnline(false);}
 },[mode]);
 useEffect(()=>{const initial=setTimeout(load,0);const timer=setInterval(load,1000);const refresh=()=>void load();window.addEventListener('online',refresh);window.addEventListener('focus',refresh);return()=>{clearTimeout(initial);clearInterval(timer);window.removeEventListener('online',refresh);window.removeEventListener('focus',refresh);};},[load]);
 async function post(path:string,data:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:AbortSignal.timeout(10000)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await post('/api/host/login',{secret});setSecret('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function act(action:Action,eventId?:string,ms?:number,reason?:string){
  if(!view||(busy&&action!=='stop'))return;setBusy(true);setError('');
  try{const d=await post('/api/host/command',{mode,runId:view.id,requestId:crypto.randomUUID(),action,eventId,ms,reason});setView(d);setConfirmation(null);if(action==='preflight')setTab('preflight');}catch(e){setError(action==='stop'?'STOP wurde vom Server nicht bestätigt. Bitte die Experience sofort persönlich unterbrechen und alle Spielerinnen informieren.':(e as Error).message);await load();}finally{setBusy(false);}
 }
 async function link(playerId:string,revoke=false){
  setBusy(true);setError('');try{const d=await post('/api/host/link',{mode,playerId,revoke});setLinks(old=>{const next={...old};if(d.link)next[playerId]=location.origin+d.link;else delete next[playerId];return next;});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 if(needsLogin)return <main className="gate"><span className="eyebrow">NACHTRAG / CONTROL</span><h1>Ein geschützter Raum.</h1><p>Host-Zugang und persönliche Player-Zugänge sind getrennt.</p><form onSubmit={login}><label>Host-Zugang<input type="password" value={secret} onChange={e=>setSecret(e.target.value)} autoComplete="current-password" required/></label><button className="primary" disabled={busy}>Control öffnen</button></form>{error&&<p role="alert" className="error">{error}</p>}</main>;
 if(!view||view.mode!==mode)return <main className="gate"><span className="eyebrow">NACHTRAG / CONTROL</span><h1>Control verbinden</h1><p role="status">{online?'Serverzustand wird geladen.':'Server nicht erreichbar. Es wurde kein neuer Zustand bestätigt.'}</p></main>;
 const pending=view.events.filter(e=>!['DELIVERED','ACKNOWLEDGED','SKIPPED','CANCELLED'].includes(e.status));
 const next=pending.find(e=>e.id!=='manual');
 const safety=view.players.filter(p=>p.safety);
 const canOverride=['LIVE','PAUSED'].includes(view.state)&&online&&!busy;
 return <div className="control-shell">
  <header className="topbar"><a className="brand" href="/control">NACHTRAG<span>CONTROL</span></a><div className="top-status"><span className={`dot ${online?'':'red'}`}/>{online?'SERVER VERBUNDEN':'OFFLINE'}</div><button className="quiet logout" onClick={async()=>{await post('/api/logout',{});setNeedsLogin(true);setView(null);setLinks({});}}>Abmelden</button></header>
  <main className="control-main">
   <div className="intro"><div><span className="eyebrow">PRIVATE EXPERIENCE / VIER SPIELERINNEN</span><h1>Der Abend. Unter Kontrolle.</h1><p>DEMO Scenario · {view.version} {view.versionLocked?'· Version eingefroren':''}</p></div><label className="mode-label">RUN<select aria-label="Run Mode" value={mode} onChange={e=>{requestEpoch.current++;setConfirmation(null);setMode(e.target.value as Mode);setView(null);setLinks({});setError('');}}><option value="test">DEMO · TEST MODE</option><option value="live">DEMO · LIVE RUN</option></select></label></div>
   <nav className="tabs" aria-label="Control-Bereiche">{(['live','preflight','log'] as const).map(t=><button key={t} className={tab===t?'selected':''} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{t==='live'?'Live Control':t==='preflight'?'Pre-flight':'Event Log'}</button>)}</nav>
   {(!online||error)&&<section className="alert" role="alert"><b>{online?'AKTION NICHT BESTÄTIGT':'VERBINDUNG UNTERBROCHEN'}</b><p>{error||'Letzter bestätigter Stand. Steueraktionen sind gesperrt; nach Reconnect wird der Serverzustand geladen.'}</p></section>}
   {safety.length>0&&<section className="alert safety-alert" role="alert"><b>SAFETY · ACTION NEEDED</b><p>{safety.map(p=>p.displayName).join(', ')} hat die Experience gestoppt. Bitte persönlich nachfragen. Der persönliche Safety-Stop bleibt bis zu einem neuen Run bestehen.</p></section>}
   {view.state==='STOPPED'&&<section className="alert safety-alert"><b>STOPPED · AUTOMATION GESPERRT</b><p>Alle Player sind im sicheren Zustand. Kein späteres Event kann diesen Stop überschreiben.</p></section>}
   <section className="status-strip"><div><span className="eyebrow">EXPERIENCE STATE</span><strong className={view.state==='LIVE'?'live-state':''}>{view.state}</strong></div><div><span className="eyebrow">STORY CLOCK</span><strong className="clock">{duration(view.storyTime)}</strong></div><div className="wall-clock"><span className="eyebrow">BERLIN / WALL CLOCK</span><strong className="clock">{wall(view.wallNow)}</strong></div><div><span className="eyebrow">PAUSENDAUER</span><strong className="clock small">{duration(view.pausedTotal)}</strong></div></section>
   {tab==='live'&&<>
    <div className="live-grid"><section className="panel now"><span className="eyebrow">NOW</span><h2>{view.state==='LIVE'?'Die Engine führt. Du bleibst dabei.':view.state==='PAUSED'?'Ein Moment Ruhe.':view.state==='STOPPED'?'Sicher gestoppt.':'Bereit für den ersten Impuls.'}</h2><p>{view.state==='LIVE'?'Zeit, Inhalte und Antworten werden serverseitig zusammengeführt.':view.state==='PAUSED'?'Die Story Clock ist eingefroren. Safety bleibt erreichbar.':'Vier persönliche Zugänge einrichten, Pre-flight prüfen und bewusst starten.'}</p><div className="button-row main-actions">
     {['DRAFT','VALIDATED','READY'].includes(view.state)&&<button className="primary" disabled={busy||!online} onClick={()=>act('preflight')}>PRE-FLIGHT</button>}
     {view.state==='READY'&&<button className="primary" disabled={busy||!online} onClick={()=>act('arm')}>ARM</button>}
     {view.state==='ARMED'&&<button className="primary" disabled={busy||!online} onClick={()=>act('start')}>LIVE starten</button>}
     {view.state==='LIVE'&&<button className="primary" disabled={busy||!online} onClick={()=>act('pause')}>PAUSE</button>}
     {view.state==='PAUSED'&&<button className="primary" disabled={busy||!online} onClick={()=>act('resume')}>RESUME</button>}
    </div></section><section className="panel next"><span className="eyebrow">NEXT</span><h2>{next?.title||'Kein automatisches Event offen'}</h2><p>{next?.scheduledAt!==null&&next?.scheduledAt!==undefined?`Story-Zeit ${duration(next.scheduledAt)} · noch ${duration(Math.max(0,next.scheduledAt-view.storyTime))}`:next?.id==='choice'?'Wartet auf Janines Bestätigung + 30 Sekunden.':'Freigabe über Anchor und serverseitige Abhängigkeiten.'}</p><span className="badge">{next?.status||'RUHIG'}</span></section></div>
    <section className="section-heading"><div><span className="eyebrow">PLAYERS</span><h2>Vier Zugänge. Ein gemeinsamer Abend.</h2></div><span className="muted">Persönlich · getrennt · widerrufbar</span></section>
    <div className="players">{view.players.map((p,i)=><section className="panel player-card" key={p.id}><div className="player-top"><span className="player-number">0{i+1}</span><span className={`badge ${p.safety?'red-text':''}`}>{p.safety?'SAFETY STOP':p.online?'ONLINE':p.lastSeen?'OFFLINE':'NICHT GEÖFFNET'}</span></div><h3>{p.displayName}</h3><p>{p.content?.title||'Noch kein Inhalt freigegeben'}</p><p className="muted">{p.lastInteraction?`Antwort: ${p.lastInteraction}`:p.linked?'Zugang eingerichtet':'Zugang fehlt'}{p.lastSeen?` · zuletzt ${wall(p.lastSeen)}`:''}</p><div className="button-row"><button className="quiet" disabled={busy||!online} onClick={()=>link(p.id)}>{p.linked?'Link neu erzeugen':'Player-Link erzeugen'}</button>{p.linked&&<button className="quiet" disabled={busy||!online} onClick={()=>link(p.id,true)}>Widerrufen</button>}</div>{links[p.id]&&<div className="link-box"><label>Einmaliger Link<input aria-label={`${p.displayName} Player-Link`} value={links[p.id]} readOnly onFocus={e=>e.target.select()}/></label><a href={links[p.id]} target="_blank" rel="noreferrer">Player öffnen ↗</a><p>Nur einmal nutzbar. Ein neuer Link widerruft alte Sessions.</p></div>}</section>)}</div>
    <section className="section-heading"><div><span className="eyebrow">WAITING / MANUAL OVERRIDE</span><h2>Jeder Schritt bleibt nachvollziehbar.</h2></div></section>
    <section className="panel event-list">{view.events.map(e=><div className="event-row" key={e.id}><div><b>{e.title}</b><p>{e.dependencies.length?`Abhängig von ${e.dependencies.map(d=>`${d.eventId} · ${d.status}`).join(', ')}`:e.trigger.type==='manual'?'Nur bewusste Host-Freigabe':`${e.trigger.anchor} + ${e.trigger.offset/1000}s${e.delay?` + ${e.delay/1000}s Delay`:''}`}</p></div><span className="badge">{e.status}</span>{!['DELIVERED','ACKNOWLEDGED','SKIPPED','CANCELLED'].includes(e.status)&&<div className="button-row"><button className="quiet" disabled={!canOverride||view.state!=='LIVE'} onClick={()=>setConfirmation({action:'fire',eventId:e.id})}>Auslösen</button><button className="quiet" disabled={!canOverride} onClick={()=>setConfirmation({action:'delay',eventId:e.id})}>+1 Min.</button><button className="quiet" disabled={!canOverride} onClick={()=>setConfirmation({action:'skip',eventId:e.id})}>Überspringen</button></div>}</div>)}</section>
    {mode==='test'&&<section className="panel test-lab"><div><span className="eyebrow">TEST LAB / VIRTUELLE CLOCK</span><h2>Minuten statt eines ganzen Abends.</h2><p>Nur der Test Run verändert sich. Player-Links sind echte getrennte Sessions.</p></div><div className="button-row">{[1,5,30].map(m=><button key={m} className="quiet" disabled={busy||!online||view.state==='STOPPED'} onClick={()=>act('advance',undefined,m*60000)}>Zeit +{m} Min.</button>)}<button className="quiet" disabled={busy||!online} onClick={()=>setConfirmation({action:'reset'})}>Test Reset</button></div></section>}
    <section className="system-panel"><span className="eyebrow">SYSTEM</span><p><span className="dot"/> Datenbank: {view.database}</p><p>Aktualisierung: Server-Refetch / 1 Sekunde</p><p className={view.scheduler.healthy?'':'warning-text'}>Scheduler: {view.scheduler.healthy?'Worker aktiv':'Worker nicht bestätigt · Catch-up bei Zugriff'}</p><p>Session: {duration(view.sessionElapsed)} · {view.snapshots.length} Snapshots</p></section>
   </>}
   {tab==='preflight'&&<section className="panel"><span className="eyebrow">PRE-FLIGHT</span><h2>Vor dem Start. Ohne Überraschungen.</h2><p>Kritische Fehler blockieren ARM. Warnungen benennen echte Betriebsgrenzen.</p>{view.preflight.length?view.preflight.map(c=><div className="check-row" key={c.name}><span className={`badge ${c.status==='FAIL'?'red-text':c.status==='WARNING'?'warning-text':''}`}>{c.status}</span><div><b>{c.name}</b><p>{c.detail}</p></div></div>):<p>Noch nicht ausgeführt. Alle vier Player-Zugänge erzeugen und PRE-FLIGHT starten.</p>}<div className="button-row">{['DRAFT','READY'].includes(view.state)&&<button className="primary" disabled={busy||!online} onClick={()=>act('preflight')}>PRE-FLIGHT</button>}{view.state==='READY'&&<button className="primary" disabled={busy||!online} onClick={()=>act('arm')}>ARM</button>}{view.state==='ARMED'&&<button className="primary" disabled={busy||!online} onClick={()=>{void act('start');setTab('live');}}>LIVE starten</button>}</div></section>}
   {tab==='log'&&<section className="panel"><span className="eyebrow">EVENT LOG / SERVER AUDIT</span><h2>Was geschah. Und warum.</h2><p>Die letzten 150 Einträge dieses Runs. UTC gespeichert, hier Berlin. Alte Test Runs bleiben im Datenbank-Archiv.</p>{view.audit.map(entry=><div className="log-row" key={entry.id}><time>{wall(entry.timestamp)}</time><div><b>{entry.action}</b><p>{entry.actor} {entry.playerId?`· ${view.players.find(p=>p.id===entry.playerId)?.displayName}`:''} {entry.eventId?`· ${entry.eventId}`:''}</p><p>{entry.reason}</p>{entry.before&&<p>{entry.before} → {entry.after}</p>}</div><span className="muted">#{entry.id}</span></div>)}</section>}
  </main>
  <footer className="safety-dock"><div><b>SAFETY HAT VORRANG</b><span>Global stoppen · persistent · neutral</span></div><button className="danger" disabled={view.state==='STOPPED'} onClick={()=>setConfirmation({action:'stop'})}>STOP ALL</button></footer>
  {confirmation&&<Confirm action={confirmation} onCancel={()=>setConfirmation(null)} onConfirm={reason=>act(confirmation.action,confirmation.eventId,undefined,reason)}/>}
 </div>;
}
